Кузь Володимир МСС-3                                                                                                        
Лабораторна робота №2                                                                                                        
Чисельне розв'язання СЛАР

In [1]:
from sympy import *
from mpmath import *
import math
import numpy as np
import pprint

In [2]:
n = 5
m = 5
e = 10**(-6)
q = 0.9
b = np.random.rand(n, 1)
print(b)
A = randMatrix(n, m)
pprint.pprint(A)
R = randmatrix(n, m)
pprint.pprint(R)

[[0.09201538]
 [0.48487664]
 [0.94351586]
 [0.35392359]
 [0.59934778]]
Matrix([
[49,  8, 80, 34, 39],
[ 6, 88, 60, 39, 49],
[20, 41, 78, 83, 46],
[28,  9, 76, 96, 85],
[23, 48, 51, 44,  1]])
matrix(
[['0.294421481433894', '0.977842345034247', '0.888192630997564', '0.583434526927709', '0.232894928233909'],
 ['0.973706187848387', '0.255908611100522', '0.246118993419553', '0.0346266616168998', '0.819754142800366'],
 ['0.226372898000763', '0.544498231815092', '0.326772019472997', '0.463244864857989', '0.284012942329279'],
 ['0.512090645666222', '0.339246435283601', '0.101483357200581', '0.230559953431843', '0.330290843052788'],
 ['0.102026067964874', '0.0839724761247325', '0.828348670818065', '0.813468065128861', '0.615127700836313']])


In [3]:
def gilbert(a, b):
    return Matrix([[1 / (i + j + 1) for j in range(b)] for i in range(a)])
G = gilbert(5,5)
pprint.pprint(G)
print(hilbert(5))

Matrix([
[              1.0,               0.5, 0.333333333333333,              0.25,               0.2],
[              0.5, 0.333333333333333,              0.25,               0.2, 0.166666666666667],
[0.333333333333333,              0.25,               0.2, 0.166666666666667, 0.142857142857143],
[             0.25,               0.2, 0.166666666666667, 0.142857142857143,             0.125],
[              0.2, 0.166666666666667, 0.142857142857143,             0.125, 0.111111111111111]])
[              1.0                0.5  0.333333333333333               0.25                0.2]
[              0.5  0.333333333333333               0.25                0.2  0.166666666666667]
[0.333333333333333               0.25                0.2  0.166666666666667  0.142857142857143]
[             0.25                0.2  0.166666666666667  0.142857142857143              0.125]
[              0.2  0.166666666666667  0.142857142857143              0.125  0.111111111111111]


In [4]:
def check_res(A, b, x, n):
    res = np.zeros(n)
    for i in range(n):
        s = 0
        for j in range(n):
            s += A[i, j] * x[j]
        res[i] = s - b[i]
    print(res)

# Метод Якобі

In [21]:
def new_matrix(A, q, n):
    A_j = A
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += A_j[i, j]
        if q*A_j[i,i] < abs(s):
            A_j[i,i] = abs(s)/q + 1
    return A_j
A_j = new_matrix(A, q, n)
pprint.pprint(A_j)

Matrix([
[179.888888888889,                6,               20,    28,               23],
[               6, 172.111111111111,               41,     9,               48],
[              20,               41, 212.111111111111,    76,               51],
[              28,                9,               76, 221.0,               44],
[              23,               48,               51,    44, 185.444444444444]])


In [22]:
def jacobi(A, b, q, eps, n):
    x = np.zeros(n)
    k = 1
    while(q**k/(1-q) > eps):
        for i in range(n):
            s = 0
            for j in range(i):
                s -= A[i,j] * x[j] / A[i,i]
            for j in range(i+1, n):
                s -= A[i, j] * x[j] / A[i, i]
            s += b[i] / A[i, i]
            x[i] = s
        k += 1
    return x
x_j = jacobi(A_j, b, q, e, n)
print(x_j)
check_res(A_j, b, x_j, n)

[-0.00017894  0.00140523  0.00378063 -0.00010672  0.00187601]
[ 0.00000000e+00 -5.55111512e-17  1.11022302e-16  0.00000000e+00
  0.00000000e+00]


# Метод Зеделя

In [7]:
def new_seidel_matrix(A, q, n):
    A_s = A_j
    for i in range(n-1):
        for j in range(i+1, n):
            A_s[i, j] = A_s[j, i]
    return A_s
A_s = new_seidel_matrix(А, q, n)
pprint.pprint(A_s)

Matrix([
[179.888888888889,                6,               20,    28,               23],
[               6, 172.111111111111,               41,     9,               48],
[              20,               41, 212.111111111111,    76,               51],
[              28,                9,               76, 221.0,               44],
[              23,               48,               51,    44, 185.444444444444]])


In [24]:
def seidel(A, b, q, eps, n):
    x = np.zeros(n)
    x_1 = np.copy(x)
    k = 1
    while(q**k/(1-q) > eps):
        for i in range(n):
            s = 0
            for j in range(i):
                s -= A[i, j] * x_1[j] / A[i, i]
            for j in range(i+1, n):
                s -= A[i, j] * x[j] / A[i, i]
            s += b[i] / A[i, i]
            x_1[i] = s
        k += 1
        x = x_1
    return(x)
x_s = seidel(A_s, b, q, e, n)
print(x_s)
check_res(A_s, b, x_s, n)

[-0.00017894  0.00140523  0.00378063 -0.00010672  0.00187601]
[ 0.00000000e+00 -5.55111512e-17  1.11022302e-16  0.00000000e+00
  0.00000000e+00]


# Метод Гауса

In [9]:
P1, L1, U1 = lu(A)
print(L1)
print(P1)
print(U1)

[               1.0                 0.0                0.0               0.0  0.0]
[0.0333539221741816                 1.0                0.0               0.0  0.0]
[ 0.111179740580605   0.234615146621742                1.0               0.0  0.0]
[ 0.155651636812847  0.0469201549753185  0.354220334145741               1.0  0.0]
[ 0.127856701667696   0.274751837886715  0.186410670085709  0.13065234730043  1.0]
[1.0  0.0  0.0  0.0  0.0]
[0.0  1.0  0.0  0.0  0.0]
[0.0  0.0  1.0  0.0  0.0]
[0.0  0.0  0.0  1.0  0.0]
[0.0  0.0  0.0  0.0  1.0]
[179.888888888889               6.0              20.0              28.0              23.0]
[             0.0  171.910987578066  40.3329215565164  8.06609017912291  47.2328597899938]
[             0.0               0.0  200.424801994834  70.9945403337039  37.3613216416525]
[             0.0               0.0               0.0  191.115582168463  24.9696994159979]
[             0.0               0.0               0.0               0.0  159.299526427547]


In [10]:
def LU(A, n):
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i <= j:
                s1 = 0
                for k in range(i): 
                    s1 += L[i, k] * U[k, j]
                U[i, j] = (A[i, j] - s1) 
            else:
                s2 = 0
                for k in range(j): 
                    s2 += L[i, k] * U[k, j]
                L[i, j] = (A[i, j] - s2) / U[j, j]
    return([L, U])
L, U = LU(A, n)
print(L)
print(U)

[[1.         0.         0.         0.         0.        ]
 [0.03335392 1.         0.         0.         0.        ]
 [0.11117974 0.23461515 1.         0.         0.        ]
 [0.15565164 0.04692015 0.35422033 1.         0.        ]
 [0.1278567  0.27475184 0.18641067 0.13065235 1.        ]]
[[179.88888889   6.          20.          28.          23.        ]
 [  0.         171.91098758  40.33292156   8.06609018  47.23285979]
 [  0.           0.         200.42480199  70.99454033  37.36132164]
 [  0.           0.           0.         191.11558217  24.96969942]
 [  0.           0.           0.           0.         159.29952643]]


In [16]:
def gauss(A, L, U, b):
    L_i = np.linalg.inv(L)
    U_i = np.linalg.inv(U)
    y = np.dot(L_i, b)
    x = np.dot(U_i, y)
    return x
x_g = gauss(A, L, U, b)
print(x_g)
check_res(A, b, x_g, n)

[[-0.00017894]
 [ 0.00140523]
 [ 0.00378063]
 [-0.00010672]
 [ 0.00187601]]
[ 0.00000000e+00 -5.55111512e-17  0.00000000e+00  0.00000000e+00
  0.00000000e+00]
